all:
	gcc src/web_robotstofzuiger.c -o robotstofzuiger.cgi -Wall -Wextra -Wconversion -ansi -pedantic `mariadb_config --libs` -I "./inc"
	gcc src/web_airco.c -o airco.cgi -Wall -Wextra -Wconversion -ansi -pedantic `mariadb_config --libs` -I "./inc"
